var MapGen = MapGen || {};
MapGen.Terrain = MapGen.Terrain || {};

MapGen.Terrain.TileCatalog = {

    NeighborOrder: [
        "northWest",
        "north",
        "northEast",
        "west",
        "east",
        "southWest",
        "south",
        "southEast"
    ],

    Jungle: {
        name: "CF1 jungle",
        supportsWater: true,
        waterPolicy: {
            rivers: true,
            ponds: true,
            // Random jungle maps use junsub0 for huts; beach art lives in junsub1
            // at the same tile IDs, so coast/beach tiles need an explicit opt-in.
            coasts: false,
            crossings: true,
            style: "jungle_swamp",
            maxRiverWidth: 4,
            maxPondRadius: 5,
            maxCoverage: 0.32
        },

        palette: {
            grass: [124, 124, 124, 124, 124, 124, 124, 123, 123, 123],
            tree: [1, 2],
            water: [326, 346],
            riverBank: [107, 167],
            beach: [256, 257, 258, 259, 324],
            ford: [20],
            crossing: [20],
            jungleEdge: [0, 0, 0, 0, 20, 20, 40, 40, 18],
            featureGround: [0, 0, 0, 0, 20, 20, 40, 40, 18]
        },

        stamps: {
            riverBend: [346],
            bankAccent: [107, 167],
            fordApproach: [0, 20, 40],
            hutClearing: [0, 20, 40],
            baseEntrance: [0, 20, 40],
            beach: [256, 257, 258, 259, 324],
            roughGround: [123, 124],
            bloom: [74],
            palmBase: [58],
            bushTopLeft: [50],
            bushTopRight: [51],
            bushBottomLeft: [70],
            bushBottomRight: [71]
        },

        families: [
            {
                id: "path",
                tiles: [0, 20, 40],
                use: "Open light grass used for routes, crossings, clearing interiors, structure approaches, and protected feature ground.",
                relationship: "Smoothed as path against dark grass and trees; protected path cells are not converted into tree or water transitions."
            },
            {
                id: "grass",
                tiles: [123, 124],
                use: "Default jungle floor and dark-grass field between paths, trees, banks, and open spaces.",
                relationship: "Acts as the ground side of transition bitmasks for water, light grass, swamp banks, and trees."
            },
            {
                id: "beach",
                tiles: [256, 257, 258, 259, 324],
                use: "Walkable jungle beach and landing-strip shore material.",
                relationship: "Painted on planned coast/beach bands. Beach-to-grass and water-to-beach bitmasks replace exposed edge cells, while interiors stay on solid sand tiles."
            },
            {
                id: "tree",
                tiles: [1, 2],
                use: "Base tree mask seed tiles before tree canopy bitmask rules replace connected tree shapes.",
                relationship: "Tree rules read connected blocked neighbours and replace top, middle, and bottom canopy cells as a multi-tile vertical object."
            },
            {
                id: "water",
                tiles: [326, 346],
                use: "River and pond interiors.",
                relationship: "Water-to-ground bitmask rules replace edge water cells where neighbouring cells are ground, path, or bank."
            },
            {
                id: "riverBank",
                tiles: [107, 167],
                use: "Sparse swampy sink bank accents around deliberate pond/swamp pockets.",
                relationship: "These tiles have sink terrain behaviour in the jungle HIT data, so they are used as rare soft-hazard material and not as river edging, protected ford, or route material."
            },
            {
                id: "quicksandTransition",
                tiles: [146, 147, 148, 166, 168, 186, 187, 188, 206, 207, 208, 226, 227],
                use: "Smoothed swamp and quicksand transition tiles written by jungle bank bitmask rules.",
                relationship: "Generated by `bm_cf1_jungle_swamp_darkgrass`; treated as soft-hazard edge material, not ordinary ground."
            },
            {
                id: "decor",
                tiles: [50, 51, 58, 70, 71, 74],
                use: "Small terrain decorations under planned palms, shrubs, and blooms.",
                relationship: "Only stamped after terrain smoothing and only on non-critical readable ground."
            }
        ],

        transitions: [
            {
                id: "waterDarkgrass",
                dataName: "bm_cf1_jungle_water_darkgrass",
                center: "water",
                ground: "grass",
                extras: ["path", "riverBank"],
                relationship: "A bit value of 0 means the neighbouring cell is water; 1 means it is grass, path, or bank."
            },
            {
                id: "lightgrassDarkgrass",
                dataName: "bm_cf1_jungle_lightgrass_darkgrass",
                center: "path",
                ground: "grass",
                extras: ["tree", "riverBank"],
                relationship: "A bit value of 0 means the neighbouring cell is path; 1 means it is grass, tree, or bank."
            },
            {
                id: "swampDarkgrass",
                dataName: "bm_cf1_jungle_swamp_darkgrass",
                center: "riverBank",
                ground: "grass",
                extras: ["path", "tree"],
                relationship: "A bit value of 0 means the neighbouring cell is bank; 1 means it is grass, path, or tree."
            },
            {
                id: "treeCanopy",
                dataName: "bm_cf1_jungle_tree",
                center: "tree",
                ground: "grass",
                relationship: "Tree bitmasks use the same neighbour order and replace connected tree cells as top, middle, and bottom canopy parts."
            }
        ]
    },

    Ice: {
        name: "CF1 ice",
        supportsWater: true,
        waterPolicy: {
            rivers: true,
            ponds: true,
            lakes: true,
            coasts: false,
            crossings: false,
            style: "icy_water",
            maxRiverWidth: 3,
            maxPondRadius: 4,
            maxLakeCount: 3,
            maxLakeRadius: 7,
            maxCoverage: 0.30
        },

        palette: {
            grass: [0, 0, 1],
            tree: [213, 233],
            water: [100, 100, 101, 102],
            riverBank: [84],
            ford: [0, 1],
            crossing: [0, 1],
            jungleEdge: [0, 1],
            featureGround: [0, 1]
        },

        stamps: {
            riverBend: [100, 101, 102],
            bankAccent: [84],
            fordApproach: [0, 1],
            hutClearing: [0, 1],
            baseEntrance: [0, 1],
            beach: [0, 1],
            roughGround: [0, 1]
        },

        families: [
            {
                id: "snow",
                tiles: [0, 1],
                use: "Walkable snow and dry ice for clear terrain and safe routes.",
                relationship: "`0|1` is the generated safe ground pair. Other profiled dry-ice IDs such as `13`, `45`, `19`, `25`, `17`, `9`, and `63` need whole-patch or bitmask placement before they can be emitted without unsupported borders."
            },
            {
                id: "wetIce",
                tiles: [20, 21, 33, 34, 84],
                use: "Walkable wet-ice edge material around water and route shoulders.",
                relationship: "Generated ice uses a stable cardinal bank ring, then writes authored water-edge bitmasks and map-derived river triples over it. `20|21|33|34|84` can appear as explicit bank/wet-edge material; support IDs such as `3..25`, `42..45`, `62`, and `63` are emitted only by boundary rules."
            },
            {
                id: "water",
                tiles: [100, 101, 102],
                use: "Water and deep-ice water bodies.",
                relationship: "Water interiors use the profiled `100|101|102` family. Edge water IDs are emitted by the CF1 ice water bitmasks and by authored left/right/top/bottom river-bank triples so bank faces and adjacent shallow water stay in complete original-map combinations."
            },
            {
                id: "blockedIce",
                tiles: [152, 153, 154, 155, 157, 159, 170, 171, 172, 173, 174, 175, 190, 191, 192, 193, 194, 195, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 230, 231, 232, 233, 234, 235],
                use: "Blocking ice outcrops and solid cover.",
                relationship: "Connected ice cover is rendered by a compact tree runtime table generated from TileTagger trunk stacks plus pixel-derived green-tile edge connectivity. `leftedge` and `rightedge` stamps are bottom-of-column stacks only; canopy/top cells are selected from pixel-connectivity candidates."
            },
            {
                id: "iceJumpRamp",
                tiles: [35, 36, 55, 56, 74, 75, 76, 77, 38, 39, 58, 59],
                use: "Rare vehicle jump ramps in ice missions.",
                relationship: "Jump ramps are stamped only as complete authored shapes on clear `0|1` snow, with a clean snow margin and no protected route, water, bank, blocker, or occupied feature overlap. Current authored data covers down, up, and left-facing ramps; no right-facing ramp is emitted."
            },
            {
                id: "iceFence",
                tiles: [245, 246, 247, 264, 265, 267, 284, 285, 287],
                use: "Rare small ice fence/structure stamp.",
                relationship: "Fence tiles are emitted as a complete 3x3 shape on clear snow only. They use the same protected-route and clean-margin rules as jump ramps so they stay out of paths, crossings, structures, water, and cover."
            }
        ],

        transitions: []
    },

    // Only Jungle and Ice palettes ship. Unsupported terrain profiles are
    // rejected before generation reaches tile catalog/rendering.
    ProfileForTerrain: function(pTerrainType) {
        if(typeof Terrain === "undefined")
            return this.Jungle;

        if(pTerrainType === Terrain.Types.Jungle)
            return this.Jungle;

        if(pTerrainType === Terrain.Types.Ice)
            return this.Ice;

        // P1.3 (v3 author contract): tagged with RendererUnsupportedIntent enum
        // string per v3.4 §3.5 + AuthorReason.RendererUnsupportedIntent so future
        // analytics can group renderer-dispatch bug-guards. v3 Concept.appliesTo()
        // gate prevents this dispatch from being called with an unsupported
        // TerrainType, so this remains a programmer-bug-guard, not an expected
        // candidate failure. See Documentation/Future/Phase0/D7_author_contract.md.
        throw "RendererUnsupportedIntent: Unsupported terrain catalog TerrainType: " + pTerrainType;
    },

    PaletteForTerrain: function(pTerrainType) {
        return this.ProfileForTerrain(pTerrainType).palette;
    },

    StampsForTerrain: function(pTerrainType) {
        return this.ProfileForTerrain(pTerrainType).stamps;
    },

    SupportsWater: function(pTerrainType) {
        var profile = this.ProfileForTerrain(pTerrainType);
        return profile.supportsWater !== false && profile.palette && profile.palette.water && profile.palette.water.length > 0;
    },

    WaterPolicyForTerrain: function(pTerrainType) {
        var profile = this.ProfileForTerrain(pTerrainType);

        return profile.waterPolicy || {
            rivers: this.SupportsWater(pTerrainType),
            ponds: this.SupportsWater(pTerrainType),
            coasts: false,
            style: "generic"
        };
    },

    SupportsWaterFeature: function(pTerrainType, pFeature) {
        var policy = this.WaterPolicyForTerrain(pTerrainType);

        if(!this.SupportsWater(pTerrainType))
            return false;

        return policy[pFeature] !== false;
    },

    JungleBeachTilesAllowed: function(pProfile) {
        if(typeof Terrain === "undefined" || !pProfile)
            return false;
        if(pProfile.TerrainType !== Terrain.Types.Jungle)
            return true;

        return Number(pProfile.TerrainTypeSub || 0) === 1 && pProfile.AllowJungleBeachTiles === true;
    },

    SupportsWaterFeatureForProfile: function(pProfile, pFeature) {
        if(!pProfile)
            return false;

        if(typeof Terrain !== "undefined" &&
            pFeature === "coasts" &&
            pProfile.TerrainType === Terrain.Types.Jungle) {
            return this.JungleBeachTilesAllowed(pProfile);
        }

        return this.SupportsWaterFeature(pProfile.TerrainType, pFeature);
    },

    MaxWaterCoverage: function(pTerrainType, pProfileLimit) {
        var policy = this.WaterPolicyForTerrain(pTerrainType);
        var profileLimit = Number(pProfileLimit);
        var policyLimit = Number(policy.maxCoverage);

        if(isNaN(profileLimit))
            profileLimit = 0.6;
        if(isNaN(policyLimit))
            return profileLimit;

        return Math.min(profileLimit, policyLimit);
    },

    TransitionData: function(pName) {
        var jungleData = MapGen.Terrain.Smoothing && MapGen.Terrain.Smoothing.JungleData;
        var iceData = MapGen.Terrain.Smoothing && MapGen.Terrain.Smoothing.IceData;

        if(jungleData && jungleData.bitmasks && jungleData.bitmasks[pName])
            return jungleData.bitmasks[pName];
        if(iceData && iceData.bitmasks && iceData.bitmasks[pName])
            return iceData.bitmasks[pName];

        return null;
    },

    TilesFromBitmaskData: function(pData) {
        var set = {};
        var tiles = [];

        if(!pData || !pData.bitmask)
            return tiles;

        for(var ruleIndex = 0; ruleIndex < pData.bitmask.length; ++ruleIndex) {
            var rule = pData.bitmask[ruleIndex];

            if(rule.tiles) {
                for(var tileIndex = 0; tileIndex < rule.tiles.length; ++tileIndex)
                    set[Number(rule.tiles[tileIndex].tile)] = true;
            }

            if(rule.change_to) {
                for(var changeIndex = 0; changeIndex < rule.change_to.length; ++changeIndex) {
                    var matrix = rule.change_to[changeIndex].matrix || [];
                    for(var rowIndex = 0; rowIndex < matrix.length; ++rowIndex) {
                        for(var colIndex = 0; colIndex < matrix[rowIndex].length; ++colIndex)
                            set[Number(matrix[rowIndex][colIndex])] = true;
                    }
                }
            }
        }

        for(var key in set) {
            if(set.hasOwnProperty(key) && !isNaN(Number(key)))
                tiles.push(Number(key));
        }

        tiles.sort(function(pLeft, pRight) {
            return pLeft - pRight;
        });

        return tiles;
    },

    JungleTransitionTiles: function(pTransitionId) {
        for(var index = 0; index < this.Jungle.transitions.length; ++index) {
            var transition = this.Jungle.transitions[index];
            if(transition.id !== pTransitionId)
                continue;

            return this.TilesFromBitmaskData(this.TransitionData(transition.dataName));
        }

        return [];
    }
};
